### PR TITLE
updated the format step to use the correct command

### PR DESCRIPTION
**Pull request by ollewis**
**What kind of change does this PR introduce?**

**Does this PR introduce a breaking change?**

**What needs to be documented once your changes are merged?**

### CODE REVIEW

**Comment by aomi** [comment]
@ollewis I have a feeling people are gonna get tripped up if the branch gets commits added without expressed approval by the author resulting in a lot merge and rebase. @rmcilwain6 thoughts?

**Comment by rmcilwain6** [comment]
My preference would be for the action to make no changes to the codebase and just tell the author that there are issues they need to fix. When this work was done I hadn't made that clear though, now a ticket has been made for this which is more explicit in what I'm looking for.

**Comment by aomi** [comment]
I think maybe instead having it branch from the point and make a PR of the actions it did? Kinda like dependabot? Athough I agree with Reed and achieving this goal via `husky` pre-commit hooks might make more sense?

**Comment by ollewis** [comment]
I looked into configuring some of this with `husky` pre-commit and pre-push hooks. It's a pretty neat tool, but I'm not sure it entirely fits what we're trying to do. I think the best would be to run the checks in the pull request workflow rather than as a pre-commit or pre-push hook.

**Comment by ollewis** [comment]
> I think it's convention to use : rather than -.

@aomi Do you mind elaborating? I'm not sure what you're referring to.

**Comment by ollewis** [comment]
I closed this as it used for testing. See [this PR](https://github.com/VikeLabs/vikelabs.ca/pull/21) instead.

**Pull request closed without merging**
